### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by kuwapa** [tburch/jsonblob#103]
Hello, I'm trying to build and self host jsonblob. But I'm getting an error. I've opened the project in IntelliJ IDEA, done a gradle sync and project build. On running Application.kt, the project runs but on opening localhost:8080, I see this error

`{"message":"Internal Server Error: Failed to inject value for parameter [jsonBlobStore] of class: jsonblob.api.http.EditorController\n\nMessage: No bean of type [jsonblob.core.store.JsonBlobStore] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).\nPath Taken: new EditorController([JsonBlobStore jsonBlobStore],GoogleAnalyticsConfig googleAnalyticsConfig,AdsenseConfig adsenseConfig)","_links":{"self":{"href":"/","templated":false}}}
`

How do I fix it and build the project?

**Comment by tburch** [comment]
Hi @kuwapa! 

You can add the following to `src/main/resources/application.yml`:
```
file-system-blob-store:
  base-path: /some/path/to/where/you/want/blobs/stored
```

This will enable the `FileSystemJsonBlobStoreConfig`, which in turn enables the `FileSystemJsonBlobStore`.
