### ISSUE TITLE
return id as response via API

### ISSUE THREAD

**Issue by whobeika** [tburch/jsonblob#12]
@tburch Is there a way to return the generated id of the stored JSON in the response instead of the actual object, so we can access it through the API at a later stage?

Thanks

**Comment by tburch** [comment]
@whobeika If you're making a [POST](https://jsonblob.com/api#post) to create a blob, check out the `Location` header; it'll have the location the blob.

**Comment by tburch** [comment]
Please reopen this if what's in the `Location` header is insufficient.
