### ISSUE TITLE
Chrome extension API

### ISSUE THREAD

**Issue by Ephapox** [tburch/jsonblob#13]
I've been working on a Chrome extension for personal use to quickly create the mock responses using the jsonblob API. My post request is having it's preflight response rejected with a 404. I'm able to make PUT/GET requests. My current work around is having my extension store blob ids made on the app and reusing them with PUT requests but it would be nice to be able to create your own as you need them.

The server seems to configured to have allow any origin and accepts a lot of headers so I don't see why it won't accept the preflight request. 

![screen shot 2016-11-24 at 11 00 17am](https://cloud.githubusercontent.com/assets/8016648/20608280/3999df28-b235-11e6-9ddd-4eb335572472.png)
-Response headers

My guess is that a configuration on the server prevents POST requests from a chrome extension but it could also be something on the chrome extension. Any ideas?

**Comment by tburch** [comment]
I don't think there's anything that's setup to explicitly block `POST` requests. What's the path you're trying to use in your request? I don't currently have a way for user's to specify their own blob ID's, but I might entertain adding that.
