### ISSUE TITLE
500 status errors on queries against API

### ISSUE THREAD

**Issue by leonardreidy** [tburch/jsonblob#14]
Many thanks for the great tool. Unfortunately, I'm getting 500 errors on queries against the API since yesterday. The code worked fine for a few days. Now it doesn't. There also seems to be a problem with the web interface. See attached image. Any guidance would be very much appreciated. 
![jsonblobwebuicrosssiterequestissue](https://cloud.githubusercontent.com/assets/1388757/21226730/b216cb9c-c2ce-11e6-8143-309c99c0eb35.png)

**Comment by tburch** [comment]
I think I got it fixed... ran out of disk space.

**Comment by tburch** [comment]
Someone created several million blobs and I ran out of Inodes on the disk (which I erroneously thought was from too much logging). Still working out what to do...

**Comment by MatthiasJost** [comment]
Thank you for providing us this great service. Let us know when we can help with something.

**Comment by tburch** [comment]
Ok, should be all better now! Sorry for the downtime.

**Comment by MatthiasJost** [comment]
It works! Thanks a lot.

**Comment by leonardreidy** [comment]
Thanks Tristan!
