### ISSUE TITLE
Cannot Save or Post

### ISSUE THREAD

**Issue by MatthiasJost** [tburch/jsonblob#15]
Currently I cannot save a Blob or Post something on https://jsonblob.com/

**Comment by tburch** [comment]
Someone created several million blobs and I ran out of Inodes on the disk (which I erroneously thought was from too much logging). Still working out what to do...

**Comment by tburch** [comment]
Same issue as #14

**Comment by tburch** [comment]
Ok, should be all better now! Sorry for the downtime.

**Comment by MatthiasJost** [comment]
Thank you! It works.
