### ISSUE TITLE
jsonblob Chrome Extension

### ISSUE THREAD

**Issue by Ephapox** [tburch/jsonblob#16]
Hey tburch,

I really appreciate you making this tool available. I made a Chrome Extension using the API so that I can keep track of jsonblobs I've made and update them instead of creating new ones all the time. I was wondering if you would be okay with me releasing it to the public. 

Here is a link to the repo if you'd like to take a look: [chrome_jsonblob](https://github.com/Ephapox/chrome_jsonblob)

**Comment by tburch** [comment]
This is great! You should also put it in the Chrome Web Store!

**Comment by Ephapox** [comment]
Just uploaded the extension

https://chrome.google.com/webstore/detail/jsonblob/cljhoojcdfijamkmaejeplcebkpindob

**Comment by tburch** [comment]
Awesome!
