### ISSUE TITLE
Update API documentation to remove references to http

### ISSUE THREAD

**Issue by Raullg98** [tburch/jsonblob#18]
I don't know why i'm receiving this error

```
let request = require('request');

var options = {
		    url:'http://jsonblob.com/api/jsonBlob/',
		    form: {"message": "as"},
		    timeout: 0,
			    headers: {
			    'Content-Type': 'application/json',
	    		'Accept': 'application/json'
	  		}
		};

		request.post(options, function(err,response,body){
			console.log(err, response.statusCode,body)

		});
```

This is how i made the request

And this is the console log
null 301 ''

I think i am missing a thing, but I don't know that

**Comment by tburch** [comment]
@Raullg98 try using `https` instead of `http`. I think I have Cloudflare setup to force https (and probably need to update the API docs and examples).

**Comment by Raullg98** [comment]
Thanks man, that was the problem

**Comment by tburch** [comment]
You may want to setup your client to follow redirects (`301`/`302`), depending on what you're doing.
