### ISSUE TITLE
jsonblob.com is down

### ISSUE THREAD

**Issue by nickerlan** [tburch/jsonblob#68]
Cloudflare sais there is an error on server.
https://jsonblob.com/

If for some reason it will be shutted down, please let me pull out the data.

**Comment by nickerlan** [comment]
UPD: it is up again but all cyrillic characters were broken

**Comment by tburch** [comment]
Thanks, Nick. I got things fixed. Not sure about the Cyrillic characters... if those worked before, they should work now.
