### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by kerembeyazit** [tburch/jsonblob#74]
Any plans for dark mode?

Thanks,
Kerem

**Comment by tburch** [comment]
Hey Kerem,
I don't currently have any plans and UI stuff isn't my forte, but I am currently working on rebuilding the backend and with that, I'm going to try to modernize the frontend, so I'll see what I can do.
Best,
Tristan

**Comment by kerembeyazit** [comment]
Thanks. If there's anything I can help with, I'd love to help.
