### ISSUE TITLE
JSON blob api POST request seems to be Broken

### ISSUE THREAD

**Issue by stripathix** [tburch/jsonblob#96]
It used to be `x-jsonblob` header which has a path of JSON blob that is created.

But looks like it is changed to `location` response header. But in JS due to CORS it is not possible to read this header.

Ref: https://stackoverflow.com/questions/43344819/reading-response-headers-with-fetch-api

Bug Fiddle https://jsfiddle.net/62L35b8z/

Maybe need to expose this header to allow the client to read its value.

**Comment by tburch** [comment]
@stripathix I'll deploy this fix tonight. I missed this in the rewrite.

**Comment by tburch** [comment]
@stripathix deployed! 🙃
